#!/bin/bash

#source base/setup-fluxbox
echo sudo aptitude -y install \
  xorg \
  fluxbox \
  thunar

# gvim!
sudo aptitude -y install \
  vim-gtk

# utils
sudo aptitude -y install \
  unison \
  apt-file \
  acpi \
  pwgen \
  sshfs \
  openssh-client \
  ntfsprogs \
  dosfstools \
  bash-completion \
  man \
  locate \
  powertop \
  unzip \
  whois \
  wget

# coding
sudo aptitude -y install \
  gcc \
  g++ \
  make

# coding docs
sudo aptitude -y install \
  gcc-doc \
  manpages \
  manpages-dev \
  glibc-doc-reference \
  manpages-posix \
  manpages-posix-dev

# graphics
sudo aptitude -y install \
  gimp \
  imagemagick \
  vlc \
  gpicview

# latex
sudo aptitude -y install \
  evince \
  texlive-latex-base \
  texlive-latex-recommended \
  texlive-latex-extra

# latex docs
#sudo aptitude -y install \
#  texlive-latex-base-doc \
#  texlive-latex-recommended-doc \
#  texlive-latex-extra-doc

# office
sudo aptitude -y install \
  openoffice.org-writer \
  openoffice.org-calc

# internet
echo sudo aptitude -y install \
  firefox \
  flashplugin-installer \
  pidgin \
  sun-java6-plugin

# lamp
echo sudo aptitude -y install \
  libapache2-mod-php5 php5-mysql mysql-server mysql-client

